class CfgPatches
{
	class Fett_Club
	{
		units[]=
		{
			"Black_and_Blue_Mandalorian",
			"Blue_Mandalorian",
			"Green_and_Brown_Mandalorian",
			"Green_and_Red_Mandalorian",
			"Green_and_Tan_Mandalorian",
			"Grey_and_Purple_Mandalorian",
			"Orange_Mandalorian",
			"Purple_Mandalorian",
			"Yellow_and_Blue_Mandalorian",
		};
		weapons[]=
		{
			"Black_and_Blue_Mandalorian_vest",
			"Black_and_Blue_Mandalorian_traditional_helmet",
			"Blue_Mandalorian_vest",
			"Blue_Mandalorian_traditional_helmet",
			"Green_and_Brown_Mandalorian_vest",
			"Green_and_Brown_Mandalorian_traditional_helmet",
			"Green_and_Red_Mandalorian_vest",
			"Green_and_Red_Mandalorian_traditional_helmet",
			"Green_and_Tan_Mandalorian_vest",
			"Green_and_Tan_Mandalorian_traditional_helmet",
			"Grey_and_Purple_Mandalorian_vest",
			"Grey_and_Purple_Mandalorian_traditional_helmet",
			"Orange_Mandalorian_vest",
			"Orange_Mandalorian_traditional_helmet",
			"Purple_Mandalorian_vest",
			"Purple_Mandalorian_traditional_helmet",
			"Yellow_and_Blue_Mandalorian_vest",
			"Yellow_and_Blue_Mandalorian_traditional_helmet",
		};
		author="Hawkeye";
		requiredAddons[]=
		{
			"ls_armor_greenfor",
			"ls_equipment_greenfor"
		};
	};
};
class CfgFactionClasses
{
	class Mandalorians
	{
		displayName= "Mandalorians";
	};
};
class CfgEditorSubcategories
{
	class Mandalorians_Categ_Fett_Club
	{
		displayName= "Fett Club";
		priority=2;
	};	
};
class CfgWeapons
{
	class ls_mandalorian_traditional_helmet;
	class ls_mandalorian_traditional_vest;
    class ls_mandalorian_standard_backpack;
    class ls_mandalorian_undersuit_uniform;
    class ls_mandalorian_rangefinder_nvg;
	class SWLW_Westar35S;
    class UniformItem;
    class VestItem;
	class ItemInfo;
    

	class Black_and_Blue_Mandalorian_traditional_helmet: ls_mandalorian_traditional_helmet
	{
		author="Hawkeye";
		scopecurator=2;
		scope=2;
		displayName="Black and Blue Mandalorian Traditional Helmet";    
		hiddenSelections[]=
		{
			"camo1",
			"visor",
			"neckTex"
		};        
        hiddenSelectionsTextures[]=
		{
            "332nd_mandalorians\Fett_Club\data\Black_and_Blue_Mandalorian_traditional_helmet.paa",
            "332nd_mandalorians\Basic\visor.paa",
            "332nd_mandalorians\Basic\neckTex.paa"
         };
		ace_hearing_protection=1;
		ace_hearing_lowerVolume=0.40000001;
		class HitpointsProtectionInfo
            {
                class Head
                {
                    hitPointName ="HitHead";
                    armor=20;
                    passThrough=0.5;
                };
                class Face
                {
                    hitPointName ="HitFace";
                    armor=20;
                    passThrough=0.30000001;
                };
			};
	};
	class Blue_Mandalorian_traditional_helmet: ls_mandalorian_traditional_helmet
	{
		author="Hawkeye";
		scopecurator=2;
		scope=2;
		displayName="Blue Mandalorian Traditional Helmet";    
		hiddenSelections[]=
		{
			"camo1",
			"visor",
			"neckTex"
		};        
        hiddenSelectionsTextures[]=
		{
            "332nd_mandalorians\Fett_Club\data\Blue_Mandalorian_traditional_helmet.paa",
            "332nd_mandalorians\Basic\visor.paa",
            "332nd_mandalorians\Basic\neckTex.paa"
         };
		ace_hearing_protection=1;
		ace_hearing_lowerVolume=0.40000001;
		class HitpointsProtectionInfo
            {
                class Head
                {
                    hitPointName ="HitHead";
                    armor=20;
                    passThrough=0.5;
                };
                class Face
                {
                    hitPointName ="HitFace";
                    armor=20;
                    passThrough=0.30000001;
                };
			};
	};
	class Green_and_Brown_Mandalorian_traditional_helmet: ls_mandalorian_traditional_helmet
	{
		author="Hawkeye";
		scopecurator=2;
		scope=2;
		displayName="Green and Brown Mandalorian Traditional Helmet";    
		hiddenSelections[]=
		{
			"camo1",
			"visor",
			"neckTex"
		};        
        hiddenSelectionsTextures[]=
		{
            "332nd_mandalorians\Fett_Club\data\Green_and_Brown_Mandalorian_traditional_helmet.paa",
            "332nd_mandalorians\Basic\visor.paa",
            "332nd_mandalorians\Basic\neckTex.paa"
         };
		ace_hearing_protection=1;
		ace_hearing_lowerVolume=0.40000001;
		class HitpointsProtectionInfo
            {
                class Head
                {
                    hitPointName ="HitHead";
                    armor=20;
                    passThrough=0.5;
                };
                class Face
                {
                    hitPointName ="HitFace";
                    armor=20;
                    passThrough=0.30000001;
                };
			};
	};
	class Green_and_Red_Mandalorian_traditional_helmet: ls_mandalorian_traditional_helmet
	{
		author="Hawkeye";
		scopecurator=2;
		scope=2;
		displayName="Green and Red Mandalorian Traditional Helmet";    
		hiddenSelections[]=
		{
			"camo1",
			"visor",
			"neckTex"
		};        
        hiddenSelectionsTextures[]=
		{
            "332nd_mandalorians\Fett_Club\data\Green_and_Red_Mandalorian_traditional_helmet.paa",
            "332nd_mandalorians\Basic\visor.paa",
            "332nd_mandalorians\Basic\neckTex.paa"
         };
		ace_hearing_protection=1;
		ace_hearing_lowerVolume=0.40000001;
		class HitpointsProtectionInfo
            {
                class Head
                {
                    hitPointName ="HitHead";
                    armor=20;
                    passThrough=0.5;
                };
                class Face
                {
                    hitPointName ="HitFace";
                    armor=20;
                    passThrough=0.30000001;
                };
			};
	};
    class Green_and_Tan_Mandalorian_traditional_helmet: ls_mandalorian_traditional_helmet
	{
		author="Hawkeye";
		scopecurator=2;
		scope=2;
		displayName="Green and Tan Mandalorian Traditional Helmet";    
		hiddenSelections[]=
		{
			"camo1",
			"visor",
			"neckTex"
		};        
        hiddenSelectionsTextures[]=
		{
            "332nd_mandalorians\Fett_Club\data\Green_and_Tan_Mandalorian_traditional_helmet.paa",
            "332nd_mandalorians\Basic\visor.paa",
            "332nd_mandalorians\Basic\neckTex.paa"
         };
		ace_hearing_protection=1;
		ace_hearing_lowerVolume=0.40000001;
		class HitpointsProtectionInfo
            {
                class Head
                {
                    hitPointName ="HitHead";
                    armor=20;
                    passThrough=0.5;
                };
                class Face
                {
                    hitPointName ="HitFace";
                    armor=20;
                    passThrough=0.30000001;
                };
			};
	};
	class Grey_and_Purple_Mandalorian_traditional_helmet: ls_mandalorian_traditional_helmet
	{
		author="Hawkeye";
		scopecurator=2;
		scope=2;
		displayName="Grey and Purple Mandalorian Traditional Helmet";    
		hiddenSelections[]=
		{
			"camo1",
			"visor",
			"neckTex"
		};        
        hiddenSelectionsTextures[]=
		{
            "332nd_mandalorians\Fett_Club\data\Grey_and_Purple_Mandalorian_traditional_helmet.paa",
            "332nd_mandalorians\Basic\visor.paa",
            "332nd_mandalorians\Basic\neckTex.paa"
         };
		ace_hearing_protection=1;
		ace_hearing_lowerVolume=0.40000001;
		class HitpointsProtectionInfo
            {
                class Head
                {
                    hitPointName ="HitHead";
                    armor=20;
                    passThrough=0.5;
                };
                class Face
                {
                    hitPointName ="HitFace";
                    armor=20;
                    passThrough=0.30000001;
                };
			};
	};
	class Orange_Mandalorian_traditional_helmet: ls_mandalorian_traditional_helmet
	{
		author="Hawkeye";
		scopecurator=2;
		scope=2;
		displayName="Orange Mandalorian Traditional Helmet";    
		hiddenSelections[]=
		{
			"camo1",
			"visor",
			"neckTex"
		};        
        hiddenSelectionsTextures[]=
		{
            "332nd_mandalorians\Fett_Club\data\Orange_Mandalorian_traditional_helmet.paa",
            "332nd_mandalorians\Basic\visor.paa",
            "332nd_mandalorians\Basic\neckTex.paa"
         };
		ace_hearing_protection=1;
		ace_hearing_lowerVolume=0.40000001;
		class HitpointsProtectionInfo
            {
                class Head
                {
                    hitPointName ="HitHead";
                    armor=20;
                    passThrough=0.5;
                };
                class Face
                {
                    hitPointName ="HitFace";
                    armor=20;
                    passThrough=0.30000001;
                };
			};
	};
	class Purple_Mandalorian_traditional_helmet: ls_mandalorian_traditional_helmet
	{
		author="Hawkeye";
		scopecurator=2;
		scope=2;
		displayName="Purple Mandalorian Traditional Helmet";    
		hiddenSelections[]=
		{
			"camo1",
			"visor",
			"neckTex"
		};        
        hiddenSelectionsTextures[]=
		{
            "332nd_mandalorians\Fett_Club\data\Purple_Mandalorian_traditional_helmet.paa",
            "332nd_mandalorians\Basic\visor.paa",
            "332nd_mandalorians\Basic\neckTex.paa"
         };
		ace_hearing_protection=1;
		ace_hearing_lowerVolume=0.40000001;
		class HitpointsProtectionInfo
            {
                class Head
                {
                    hitPointName ="HitHead";
                    armor=20;
                    passThrough=0.5;
                };
                class Face
                {
                    hitPointName ="HitFace";
                    armor=20;
                    passThrough=0.30000001;
                };
			};
	};
	class Yellow_and_Blue_Mandalorian_traditional_helmet: ls_mandalorian_traditional_helmet
	{
		author="Hawkeye";
		scopecurator=2;
		scope=2;
		displayName="Yellow and Blue Mandalorian Traditional Helmet";    
		hiddenSelections[]=
		{
			"camo1",
			"visor",
			"neckTex"
		};        
        hiddenSelectionsTextures[]=
		{
            "332nd_mandalorians\Fett_Club\data\Yellow_and_Blue_Mandalorian_traditional_helmet.paa",
            "332nd_mandalorians\Basic\visor.paa",
            "332nd_mandalorians\Basic\neckTex.paa"
         };
		ace_hearing_protection=1;
		ace_hearing_lowerVolume=0.40000001;
		class HitpointsProtectionInfo
            {
                class Head
                {
                    hitPointName ="HitHead";
                    armor=20;
                    passThrough=0.5;
                };
                class Face
                {
                    hitPointName ="HitFace";
                    armor=20;
                    passThrough=0.30000001;
                };
			};
	};
	class Black_and_Blue_Mandalorian_vest: ls_mandalorian_traditional_vest
    {
		displayName="Black and Blue Mandalorian Vest";
		hiddenSelections[]=
		{
			"camo1"
		};
        hiddenSelectionsTextures[]=
		{
			"332nd_mandalorians\Fett_Club\data\Black_and_Blue_Mandalorian_vest.paa"
		};
	};
    class Blue_Mandalorian_vest: ls_mandalorian_traditional_vest
    {
		displayName="Blue Mandalorian Vest";
		hiddenSelections[]=
		{
			"camo1"
		};
        hiddenSelectionsTextures[]=
		{
			"332nd_mandalorians\Fett_Club\data\Blue_Mandalorian_vest.paa"
		};
	};
    class Green_and_Brown_Mandalorian_vest: ls_mandalorian_traditional_vest
    {
		displayName="Green and Brown Mandalorian Vest";
		hiddenSelections[]=
		{
			"camo1"
		};
        hiddenSelectionsTextures[]=
		{
			"332nd_mandalorians\Fett_Club\data\Green_and_Brown_Mandalorian_vest.paa"
		};
	};
    class Green_and_Red_Mandalorian_vest: ls_mandalorian_traditional_vest
    {
		displayName="Green and Red Mandalorian Vest";
		hiddenSelections[]=
		{
			"camo1"
		};
        hiddenSelectionsTextures[]=
		{
			"332nd_mandalorians\Fett_Club\data\Green_and_Red_Mandalorian_vest.paa"
		};
	};
	class Green_and_Tan_Mandalorian_vest: ls_mandalorian_traditional_vest
    {
		displayName="Green and Tan Mandalorian Vest";
		hiddenSelections[]=
		{
			"camo1"
		};
        hiddenSelectionsTextures[]=
		{
			"332nd_mandalorians\Fett_Club\data\Green_and_Tan_Mandalorian_vest.paa"
		};
	};
    class Grey_and_Purple_Mandalorian_vest: ls_mandalorian_traditional_vest
    {
		displayName="Grey and Purple Mandalorian Vest";
		hiddenSelections[]=
		{
			"camo1"
		};
        hiddenSelectionsTextures[]=
		{
			"332nd_mandalorians\Fett_Club\data\Grey_and_Purple_Mandalorian_vest.paa"
		};
	};
    class Orange_Mandalorian_vest: ls_mandalorian_traditional_vest
    {
		displayName="Orange Mandalorian Vest";
		hiddenSelections[]=
		{
			"camo1"
		};
        hiddenSelectionsTextures[]=
		{
			"332nd_mandalorians\Fett_Club\data\Orange_Mandalorian_vest.paa"
		};
	};
    class Purple_Mandalorian_vest: ls_mandalorian_traditional_vest
    {
		displayName="Purple Mandalorian Vest";
		hiddenSelections[]=
		{
			"camo1"
		};
        hiddenSelectionsTextures[]=
		{
			"332nd_mandalorians\Fett_Club\data\Purple_Mandalorian_vest.paa"
		};
	};
	class Yellow_and_Blue_Mandalorian_vest: ls_mandalorian_traditional_vest
    {
		displayName="Yellow and Blue Mandalorian Vest";
		hiddenSelections[]=
		{
			"camo1"
		};
        hiddenSelectionsTextures[]=
		{
			"332nd_mandalorians\Fett_Club\data\Yellow_and_Blue_Mandalorian_vest.paa"
		};
	};

};       
class CfgVehicles
{
    class ls_mandalorian_base;
    

    class Black_and_Blue_Mandalorian: ls_mandalorian_base
	{
        author="Hawkeye";
		scopecurator=2;
		scope=2;
		displayName="Black and Blue Mandalorian";
		faction="Mandalorians";
		editorSubcategory="Mandalorians_Categ_Fett_Club";
        linkedItems[]=
		{
			"Black_and_Blue_Mandalorian_vest",
			"Black_and_Blue_Mandalorian_traditional_helmet",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"SWLB_comlink_hush98",
			"ls_mandalorian_rangefinder_nvg"
		};
		respawnLinkedItems[]=
		{
			"Black_and_Blue_Mandalorian_vest",
			"Black_and_Blue_Mandalorian_traditional_helmet",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"SWLB_comlink_hush98",
			"ls_mandalorian_rangefinder_nvg"
		};
		weapons[]=
		{
			"SWLW_Westar35C",
			"SWLW_Westar35SA",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"SWLW_Westar35C",
			"SWLW_Westar35SA",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"SWLW_Westar35C_mag",
			"SWLW_Westar35C_mag",
			"SWLW_Westar35C_mag",
			"SWLW_Westar35C_mag",
			"SWLW_Westar35C_mag",
			"SWLW_Westar35C_mag",
			"SWLW_Westar35C_mag",
			"SWLW_Westar35SA_mag",
			"SWLW_Westar35SA_mag",
			"SWLW_Westar35SA_mag"
		};
		respawnMagazines[]=
		{
			"SWLW_Westar35C_mag",
			"SWLW_Westar35C_mag",
			"SWLW_Westar35C_mag",
			"SWLW_Westar35C_mag",
			"SWLW_Westar35C_mag",
			"SWLW_Westar35C_mag",
			"SWLW_Westar35C_mag",
			"SWLW_Westar35SA_mag",
			"SWLW_Westar35SA_mag",
			"SWLW_Westar35SA_mag"
		};
		items[]=
		{
			"ACE_flashlight_MX991",
			"ACE_MapTools",
			"ACE_microDAGR",
			"FirstAidKit",
			"FirstAidKit",
			"FirstAidKit"
		};
		respawnItems[]=
		{
			"ACE_flashlight_MX991",
			"ACE_MapTools",
			"ACE_microDAGR",
			"FirstAidKit",
			"FirstAidKit",
			"FirstAidKit"
		};
    };	
    class Blue_Mandalorian: ls_mandalorian_base
	{
        author="Hawkeye";
		scopecurator=2;
		scope=2;
		displayName="Blue Mandalorian";
		faction="Mandalorians";
		editorSubcategory="Mandalorians_Categ_Fett_Club";
        linkedItems[]=
		{
			"Blue_Mandalorian_vest",
			"Blue_Mandalorian_traditional_helmet",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"SWLB_comlink_hush98",
			"ls_mandalorian_rangefinder_nvg"
		};
		respawnLinkedItems[]=
		{
			"Blue_Mandalorian_vest",
			"Blue_Mandalorian_traditional_helmet",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"SWLB_comlink_hush98",
			"ls_mandalorian_rangefinder_nvg"
		};
		weapons[]=
		{
			"SWLW_Westar35C",
			"SWLW_Westar35SA",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"SWLW_Westar35C",
			"SWLW_Westar35SA",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"SWLW_Westar35C_mag",
			"SWLW_Westar35C_mag",
			"SWLW_Westar35C_mag",
			"SWLW_Westar35C_mag",
			"SWLW_Westar35C_mag",
			"SWLW_Westar35C_mag",
			"SWLW_Westar35C_mag",
			"SWLW_Westar35SA_mag",
			"SWLW_Westar35SA_mag",
			"SWLW_Westar35SA_mag"
		};
		respawnMagazines[]=
		{
			"SWLW_Westar35C_mag",
			"SWLW_Westar35C_mag",
			"SWLW_Westar35C_mag",
			"SWLW_Westar35C_mag",
			"SWLW_Westar35C_mag",
			"SWLW_Westar35C_mag",
			"SWLW_Westar35C_mag",
			"SWLW_Westar35SA_mag",
			"SWLW_Westar35SA_mag",
			"SWLW_Westar35SA_mag"
		};
		items[]=
		{
			"ACE_flashlight_MX991",
			"ACE_MapTools",
			"ACE_microDAGR",
			"FirstAidKit",
			"FirstAidKit",
			"FirstAidKit"
		};
		respawnItems[]=
		{
			"ACE_flashlight_MX991",
			"ACE_MapTools",
			"ACE_microDAGR",
			"FirstAidKit",
			"FirstAidKit",
			"FirstAidKit"
		};
    };
    class Green_and_Brown_Mandalorian: ls_mandalorian_base
	{
        author="Hawkeye";
		scopecurator=2;
		scope=2;
		displayName="Green and Brown Mandalorian";
		faction="Mandalorians";
		editorSubcategory="Mandalorians_Categ_Fett_Club";
        linkedItems[]=
		{
			"Green_and_Brown_Mandalorian_vest",
			"Green_and_Brown_Mandalorian_traditional_helmet",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"SWLB_comlink_hush98",
			"ls_mandalorian_rangefinder_nvg"
		};
		respawnLinkedItems[]=
		{
			"Green_and_Brown_Mandalorian_vest",
			"Green_and_Brown_Mandalorian_traditional_helmet",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"SWLB_comlink_hush98",
			"ls_mandalorian_rangefinder_nvg"
		};
		weapons[]=
		{
			"SWLW_Westar35C",
			"SWLW_Westar35SA",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"SWLW_Westar35C",
			"SWLW_Westar35SA",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"SWLW_Westar35C_mag",
			"SWLW_Westar35C_mag",
			"SWLW_Westar35C_mag",
			"SWLW_Westar35C_mag",
			"SWLW_Westar35C_mag",
			"SWLW_Westar35C_mag",
			"SWLW_Westar35C_mag",
			"SWLW_Westar35SA_mag",
			"SWLW_Westar35SA_mag",
			"SWLW_Westar35SA_mag"
		};
		respawnMagazines[]=
		{
			"SWLW_Westar35C_mag",
			"SWLW_Westar35C_mag",
			"SWLW_Westar35C_mag",
			"SWLW_Westar35C_mag",
			"SWLW_Westar35C_mag",
			"SWLW_Westar35C_mag",
			"SWLW_Westar35C_mag",
			"SWLW_Westar35SA_mag",
			"SWLW_Westar35SA_mag",
			"SWLW_Westar35SA_mag"
		};
		items[]=
		{
			"ACE_flashlight_MX991",
			"ACE_MapTools",
			"ACE_microDAGR",
			"FirstAidKit",
			"FirstAidKit",
			"FirstAidKit"
		};
		respawnItems[]=
		{
			"ACE_flashlight_MX991",
			"ACE_MapTools",
			"ACE_microDAGR",
			"FirstAidKit",
			"FirstAidKit",
			"FirstAidKit"
		};
    };	
    class Green_and_Red_Mandalorian: ls_mandalorian_base
	{
        author="Hawkeye";
		scopecurator=2;
		scope=2;
		displayName="Green and Red Mandalorian";
		faction="Mandalorians";
		editorSubcategory="Mandalorians_Categ_Fett_Club";
        linkedItems[]=
		{
			"Green_and_Red_Mandalorian_vest",
			"Green_and_Red_Mandalorian_traditional_helmet",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"SWLB_comlink_hush98",
			"ls_mandalorian_rangefinder_nvg"
		};
		respawnLinkedItems[]=
		{
			"Green_and_Red_Mandalorian_vest",
			"Green_and_Red_Mandalorian_traditional_helmet",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"SWLB_comlink_hush98",
			"ls_mandalorian_rangefinder_nvg"
		};
		weapons[]=
		{
			"SWLW_Westar35C",
			"SWLW_Westar35SA",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"SWLW_Westar35C",
			"SWLW_Westar35SA",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"SWLW_Westar35C_mag",
			"SWLW_Westar35C_mag",
			"SWLW_Westar35C_mag",
			"SWLW_Westar35C_mag",
			"SWLW_Westar35C_mag",
			"SWLW_Westar35C_mag",
			"SWLW_Westar35C_mag",
			"SWLW_Westar35SA_mag",
			"SWLW_Westar35SA_mag",
			"SWLW_Westar35SA_mag"
		};
		respawnMagazines[]=
		{
			"SWLW_Westar35C_mag",
			"SWLW_Westar35C_mag",
			"SWLW_Westar35C_mag",
			"SWLW_Westar35C_mag",
			"SWLW_Westar35C_mag",
			"SWLW_Westar35C_mag",
			"SWLW_Westar35C_mag",
			"SWLW_Westar35SA_mag",
			"SWLW_Westar35SA_mag",
			"SWLW_Westar35SA_mag"
		};
		items[]=
		{
			"ACE_flashlight_MX991",
			"ACE_MapTools",
			"ACE_microDAGR",
			"FirstAidKit",
			"FirstAidKit",
			"FirstAidKit"
		};
		respawnItems[]=
		{
			"ACE_flashlight_MX991",
			"ACE_MapTools",
			"ACE_microDAGR",
			"FirstAidKit",
			"FirstAidKit",
			"FirstAidKit"
		};
    };	
	class Green_and_Tan_Mandalorian: ls_mandalorian_base
	{
        author="Hawkeye";
		scopecurator=2;
		scope=2;
		displayName="Green and Tan Mandalorian";
		faction="Mandalorians";
		editorSubcategory="Mandalorians_Categ_Fett_Club";
        linkedItems[]=
		{
			"Green_and_Tan_Mandalorian_vest",
			"Green_and_Tan_Mandalorian_traditional_helmet",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"SWLB_comlink_hush98",
			"ls_mandalorian_rangefinder_nvg"
		};
		respawnLinkedItems[]=
		{
			"Green_and_Tan_Mandalorian_vest",
			"Green_and_Tan_Mandalorian_traditional_helmet",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"SWLB_comlink_hush98",
			"ls_mandalorian_rangefinder_nvg"
		};
		weapons[]=
		{
			"SWLW_Westar35C",
			"SWLW_Westar35SA",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"SWLW_Westar35C",
			"SWLW_Westar35SA",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"SWLW_Westar35C_mag",
			"SWLW_Westar35C_mag",
			"SWLW_Westar35C_mag",
			"SWLW_Westar35C_mag",
			"SWLW_Westar35C_mag",
			"SWLW_Westar35C_mag",
			"SWLW_Westar35C_mag",
			"SWLW_Westar35SA_mag",
			"SWLW_Westar35SA_mag",
			"SWLW_Westar35SA_mag"
		};
		respawnMagazines[]=
		{
			"SWLW_Westar35C_mag",
			"SWLW_Westar35C_mag",
			"SWLW_Westar35C_mag",
			"SWLW_Westar35C_mag",
			"SWLW_Westar35C_mag",
			"SWLW_Westar35C_mag",
			"SWLW_Westar35C_mag",
			"SWLW_Westar35SA_mag",
			"SWLW_Westar35SA_mag",
			"SWLW_Westar35SA_mag"
		};
		items[]=
		{
			"ACE_flashlight_MX991",
			"ACE_MapTools",
			"ACE_microDAGR",
			"FirstAidKit",
			"FirstAidKit",
			"FirstAidKit"
		};
		respawnItems[]=
		{
			"ACE_flashlight_MX991",
			"ACE_MapTools",
			"ACE_microDAGR",
			"FirstAidKit",
			"FirstAidKit",
			"FirstAidKit"
		};
    };	
    class Grey_and_Purple_Mandalorian: ls_mandalorian_base
	{
        author="Hawkeye";
		scopecurator=2;
		scope=2;
		displayName="Grey and Purple Mandalorian";
		faction="Mandalorians";
		editorSubcategory="Mandalorians_Categ_Fett_Club";
        linkedItems[]=
		{
			"Grey_and_Purple_Mandalorian_vest",
			"Grey_and_Purple_Mandalorian_traditional_helmet",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"SWLB_comlink_hush98",
			"ls_mandalorian_rangefinder_nvg"
		};
		respawnLinkedItems[]=
		{
			"Grey_and_Purple_Mandalorian_vest",
			"Grey_and_Purple_Mandalorian_traditional_helmet",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"SWLB_comlink_hush98",
			"ls_mandalorian_rangefinder_nvg"
		};
		weapons[]=
		{
			"SWLW_Westar35C",
			"SWLW_Westar35SA",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"SWLW_Westar35C",
			"SWLW_Westar35SA",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"SWLW_Westar35C_mag",
			"SWLW_Westar35C_mag",
			"SWLW_Westar35C_mag",
			"SWLW_Westar35C_mag",
			"SWLW_Westar35C_mag",
			"SWLW_Westar35C_mag",
			"SWLW_Westar35C_mag",
			"SWLW_Westar35SA_mag",
			"SWLW_Westar35SA_mag",
			"SWLW_Westar35SA_mag"
		};
		respawnMagazines[]=
		{
			"SWLW_Westar35C_mag",
			"SWLW_Westar35C_mag",
			"SWLW_Westar35C_mag",
			"SWLW_Westar35C_mag",
			"SWLW_Westar35C_mag",
			"SWLW_Westar35C_mag",
			"SWLW_Westar35C_mag",
			"SWLW_Westar35SA_mag",
			"SWLW_Westar35SA_mag",
			"SWLW_Westar35SA_mag"
		};
		items[]=
		{
			"ACE_flashlight_MX991",
			"ACE_MapTools",
			"ACE_microDAGR",
			"FirstAidKit",
			"FirstAidKit",
			"FirstAidKit"
		};
		respawnItems[]=
		{
			"ACE_flashlight_MX991",
			"ACE_MapTools",
			"ACE_microDAGR",
			"FirstAidKit",
			"FirstAidKit",
			"FirstAidKit"
		};
    };
    class Orange_Mandalorian: ls_mandalorian_base
	{
        author="Hawkeye";
		scopecurator=2;
		scope=2;
		displayName="Orange Mandalorian";
		faction="Mandalorians";
		editorSubcategory="Mandalorians_Categ_Fett_Club";
        linkedItems[]=
		{
			"Orange_Mandalorian_vest",
			"Orange_Mandalorian_traditional_helmet",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"SWLB_comlink_hush98",
			"ls_mandalorian_rangefinder_nvg"
		};
		respawnLinkedItems[]=
		{
			"Orange_Mandalorian_vest",
			"Orange_Mandalorian_traditional_helmet",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"SWLB_comlink_hush98",
			"ls_mandalorian_rangefinder_nvg"
		};
		weapons[]=
		{
			"SWLW_Westar35C",
			"SWLW_Westar35SA",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"SWLW_Westar35C",
			"SWLW_Westar35SA",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"SWLW_Westar35C_mag",
			"SWLW_Westar35C_mag",
			"SWLW_Westar35C_mag",
			"SWLW_Westar35C_mag",
			"SWLW_Westar35C_mag",
			"SWLW_Westar35C_mag",
			"SWLW_Westar35C_mag",
			"SWLW_Westar35SA_mag",
			"SWLW_Westar35SA_mag",
			"SWLW_Westar35SA_mag"
		};
		respawnMagazines[]=
		{
			"SWLW_Westar35C_mag",
			"SWLW_Westar35C_mag",
			"SWLW_Westar35C_mag",
			"SWLW_Westar35C_mag",
			"SWLW_Westar35C_mag",
			"SWLW_Westar35C_mag",
			"SWLW_Westar35C_mag",
			"SWLW_Westar35SA_mag",
			"SWLW_Westar35SA_mag",
			"SWLW_Westar35SA_mag"
		};
		items[]=
		{
			"ACE_flashlight_MX991",
			"ACE_MapTools",
			"ACE_microDAGR",
			"FirstAidKit",
			"FirstAidKit",
			"FirstAidKit"
		};
		respawnItems[]=
		{
			"ACE_flashlight_MX991",
			"ACE_MapTools",
			"ACE_microDAGR",
			"FirstAidKit",
			"FirstAidKit",
			"FirstAidKit"
		};
    };	
    class Purple_Mandalorian: ls_mandalorian_base
	{
        author="Hawkeye";
		scopecurator=2;
		scope=2;
		displayName="Purple Mandalorian";
		faction="Mandalorians";
		editorSubcategory="Mandalorians_Categ_Fett_Club";
        linkedItems[]=
		{
			"Purple_Mandalorian_vest",
			"Purple_Mandalorian_traditional_helmet",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"SWLB_comlink_hush98",
			"ls_mandalorian_rangefinder_nvg"
		};
		respawnLinkedItems[]=
		{
			"Purple_Mandalorian_vest",
			"Purple_Mandalorian_traditional_helmet",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"SWLB_comlink_hush98",
			"ls_mandalorian_rangefinder_nvg"
		};
		weapons[]=
		{
			"SWLW_Westar35C",
			"SWLW_Westar35SA",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"SWLW_Westar35C",
			"SWLW_Westar35SA",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"SWLW_Westar35C_mag",
			"SWLW_Westar35C_mag",
			"SWLW_Westar35C_mag",
			"SWLW_Westar35C_mag",
			"SWLW_Westar35C_mag",
			"SWLW_Westar35C_mag",
			"SWLW_Westar35C_mag",
			"SWLW_Westar35SA_mag",
			"SWLW_Westar35SA_mag",
			"SWLW_Westar35SA_mag"
		};
		respawnMagazines[]=
		{
			"SWLW_Westar35C_mag",
			"SWLW_Westar35C_mag",
			"SWLW_Westar35C_mag",
			"SWLW_Westar35C_mag",
			"SWLW_Westar35C_mag",
			"SWLW_Westar35C_mag",
			"SWLW_Westar35C_mag",
			"SWLW_Westar35SA_mag",
			"SWLW_Westar35SA_mag",
			"SWLW_Westar35SA_mag"
		};
		items[]=
		{
			"ACE_flashlight_MX991",
			"ACE_MapTools",
			"ACE_microDAGR",
			"FirstAidKit",
			"FirstAidKit",
			"FirstAidKit"
		};
		respawnItems[]=
		{
			"ACE_flashlight_MX991",
			"ACE_MapTools",
			"ACE_microDAGR",
			"FirstAidKit",
			"FirstAidKit",
			"FirstAidKit"
		};
    };	
	class Yellow_and_Blue_Mandalorian: ls_mandalorian_base
	{
        author="Hawkeye";
		scopecurator=2;
		scope=2;
		displayName="Yellow and Blue Mandalorian";
		faction="Mandalorians";
		editorSubcategory="Mandalorians_Categ_Fett_Club";
        linkedItems[]=
		{
			"Yellow_and_Blue_Mandalorian_vest",
			"Yellow_and_Blue_Mandalorian_traditional_helmet",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"SWLB_comlink_hush98",
			"ls_mandalorian_rangefinder_nvg"
		};
		respawnLinkedItems[]=
		{
			"Yellow_and_Blue_Mandalorian_vest",
			"Yellow_and_Blue_Mandalorian_traditional_helmet",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"SWLB_comlink_hush98",
			"ls_mandalorian_rangefinder_nvg"
		};
		weapons[]=
		{
			"SWLW_Westar35C",
			"SWLW_Westar35SA",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"SWLW_Westar35C",
			"SWLW_Westar35SA",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"SWLW_Westar35C_mag",
			"SWLW_Westar35C_mag",
			"SWLW_Westar35C_mag",
			"SWLW_Westar35C_mag",
			"SWLW_Westar35C_mag",
			"SWLW_Westar35C_mag",
			"SWLW_Westar35C_mag",
			"SWLW_Westar35SA_mag",
			"SWLW_Westar35SA_mag",
			"SWLW_Westar35SA_mag"
		};
		respawnMagazines[]=
		{
			"SWLW_Westar35C_mag",
			"SWLW_Westar35C_mag",
			"SWLW_Westar35C_mag",
			"SWLW_Westar35C_mag",
			"SWLW_Westar35C_mag",
			"SWLW_Westar35C_mag",
			"SWLW_Westar35C_mag",
			"SWLW_Westar35SA_mag",
			"SWLW_Westar35SA_mag",
			"SWLW_Westar35SA_mag"
		};
		items[]=
		{
			"ACE_flashlight_MX991",
			"ACE_MapTools",
			"ACE_microDAGR",
			"FirstAidKit",
			"FirstAidKit",
			"FirstAidKit"
		};
		respawnItems[]=
		{
			"ACE_flashlight_MX991",
			"ACE_MapTools",
			"ACE_microDAGR",
			"FirstAidKit",
			"FirstAidKit",
			"FirstAidKit"
		};
    };	
    
};

class cfgMods
{
	author="Hawkeye";
	timepacked="1686884054";
};